[versions]
agp = "9.0.1"
libxposed = "102.0.0"
junit = "4.13.2"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

[libraries]
libxposed-api = { module = "io.github.libxposed:api", version.ref = "libxposed" }
junit = { module = "junit:junit", version.ref = "junit" }
